package com.arryn.frontiermode.boss.server.rules;

import com.arryn.frontiermode.border.common.BorderMath;
import com.arryn.frontiermode.border.common.fixture.Border;
import com.arryn.satchel.common.util.out.OUT;
import net.minecraft.core.BlockPos;
import net.minecraft.network.chat.Component;
import net.minecraft.util.RandomSource;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.Mob;
import net.minecraft.world.entity.MobSpawnType;
import net.minecraft.world.entity.ai.attributes.Attributes;
import net.minecraft.world.level.levelgen.Heightmap;
import net.minecraft.server.level.ServerLevel;

import java.util.List;
import java.util.Optional;

/**
 * Default, opinionated implementation of {@link BossRules} -- a safe baseline meant to be
 * replaced by real balance tuning later (Game Designer/playtest territory), same "safe baseline"
 * framing as {@code DefaultBorderRules.GROWTH_FACTOR}.
 */
public final class DefaultBossRules implements BossRules {

    // Placeholder layer -> mob type table. Layer 1 is Progression & Frontier Mechanics' own named
    // example (a rabbit); higher layers step up through tougher vanilla mobs. Not a locked curve.
    // Index 0 covers layer 0 (a level's very first border, per Border's own "0 for the initial
    // border" rule) the same as layer 1, since Tier 1 draws no meaningful distinction between them.
    private static final List<EntityType<? extends Mob>> LAYER_MOBS = List.of(
            EntityType.RABBIT,
            EntityType.ZOMBIE,
            EntityType.SPIDER,
            EntityType.SKELETON,
            EntityType.ZOMBIFIED_PIGLIN,
            EntityType.PILLAGER,
            EntityType.VINDICATOR,
            EntityType.RAVAGER
    );

    // Safe-baseline linear scale, same shape as DefaultBorderRules.GROWTH_FACTOR: +50% max health
    // per layer above the table's own baseline. Not a locked curve.
    private static final double HEALTH_SCALE_PER_LAYER = 0.5;

    // Border Pregeneration: how many candidate chunk-center positions choosePosition() scores
    // before picking a winner -- a tuning number ("safe baseline, replace later"), not settled by
    // border-pregeneration.md itself.
    private static final int POSITION_CANDIDATES = 5;

    // flatnessScore()'s own safe baseline: candidate height compared against four points this far
    // out in each cardinal direction. A tuning number, not an architecture decision.
    private static final int FLATNESS_SAMPLE_DISTANCE = 4;

    // flatnessScore(): a height delta at or above this many blocks scores 0 (steepest); below it
    // scales linearly toward 1 (flattest). A tuning number.
    private static final double FLATNESS_MAX_DELTA = 8.0;

    private final RandomSource rng;

    public DefaultBossRules() {
        this(RandomSource.create());
    }

    public DefaultBossRules(RandomSource rng) {
        this.rng = rng;
    }

    @Override
    public BlockPos choosePosition(ServerLevel level, Border border) {
        BlockPos best = null;
        double bestScore = Double.NEGATIVE_INFINITY;

        for (int i = 0; i < POSITION_CANDIDATES; i++) {
            BlockPos sample = BorderMath.randomPointInDisk(rng, border.center(), border.radius());
            BlockPos chunkCenter = chunkCenterOf(sample);
            // The whole border disk is already pregenerated by the time this runs (this method
            // is only ever called once BorderAPI.isPregenReady() has passed) -- reading real
            // height/block data here is safe, not a forced-generation side effect.
            BlockPos ground = level.getHeightmapPos(Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, chunkCenter);

            double score = flatnessScore(level, ground) - hazardScore(level, ground);
            if (score > bestScore) {
                bestScore = score;
                best = ground;
            }
        }

        // POSITION_CANDIDATES is a compile-time constant > 0, so best is never null here.
        return best;
    }

    private static BlockPos chunkCenterOf(BlockPos pos) {
        int chunkX = pos.getX() >> 4;
        int chunkZ = pos.getZ() >> 4;
        return new BlockPos(chunkX * 16 + 8, pos.getY(), chunkZ * 16 + 8);
    }

    @Override
    public double flatnessScore(ServerLevel level, BlockPos candidate) {
        // Safe baseline: compares candidate's own resolved height against its four cardinal
        // neighbors, FLATNESS_SAMPLE_DISTANCE blocks over -- a flat plateau scores near 1.0, a
        // sharp cliff edge scores near 0.0. Not a locked algorithm -- Game Designer/playtest
        // territory once there's something to tune.
        int centerY = level.getHeightmapPos(Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, candidate).getY();

        int maxDelta = 0;
        int[][] offsets = {
                {FLATNESS_SAMPLE_DISTANCE, 0}, {-FLATNESS_SAMPLE_DISTANCE, 0},
                {0, FLATNESS_SAMPLE_DISTANCE}, {0, -FLATNESS_SAMPLE_DISTANCE}
        };
        for (int[] offset : offsets) {
            BlockPos neighbor = new BlockPos(
                    candidate.getX() + offset[0], candidate.getY(), candidate.getZ() + offset[1]);
            int neighborY = level.getHeightmapPos(Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, neighbor).getY();
            maxDelta = Math.max(maxDelta, Math.abs(neighborY - centerY));
        }

        return Math.max(0.0, 1.0 - (maxDelta / FLATNESS_MAX_DELTA));
    }

    @Override
    public double hazardScore(ServerLevel level, BlockPos candidate) {
        // Safe baseline: 1.0 (worst) if the resolved position itself sits in a fluid (open
        // water/lava -- same heightmap-lands-in-the-fluid signal the pre-Pregeneration
        // materialize() used to check) or the column bottoms out near the world floor (void);
        // 0.0 otherwise. Not a locked algorithm.
        if (!level.getBlockState(candidate).getFluidState().isEmpty()) {
            return 1.0;
        }
        if (candidate.getY() <= level.getMinBuildHeight() + 1) {
            return 1.0;
        }
        return 0.0;
    }

    @Override
    public Optional<Mob> materialize(ServerLevel level, BlockPos position, int layer) {
        // Border Pregeneration: position was already validated (flatness/hazard-scored) against
        // real, pregenerated terrain when choosePosition() chose it -- no in-place Y-resolution
        // or liquid-column check left to do here. See border-pregeneration.md's "Worked example:
        // Boss placement, revised" and "What this changes in Boss" sections.
        EntityType<? extends Mob> type = mobTypeForLayer(layer);
        Mob mob = type.create(level);
        if (mob == null) {
            OUT.warn("[Boss] materialize(): EntityType.create returned null for " + type + " at " + position);
            return Optional.empty();
        }

        mob.moveTo(position.getX() + 0.5, position.getY(), position.getZ() + 0.5, rng.nextFloat() * 360.0F, 0.0F);
        mob.finalizeSpawn(level, level.getCurrentDifficultyAt(position), MobSpawnType.EVENT, null, null);

        applyStatScaling(mob, layer);
        tagVisibly(mob, layer);

        if (!level.addFreshEntity(mob)) {
            OUT.warn("[Boss] materialize(): addFreshEntity failed for " + type + " at " + position);
            return Optional.empty();
        }

        return Optional.of(mob);
    }

    private EntityType<? extends Mob> mobTypeForLayer(int layer) {
        int index = Math.min(Math.max(layer, 0), LAYER_MOBS.size() - 1);
        return LAYER_MOBS.get(index);
    }

    private void applyStatScaling(Mob mob, int layer) {
        double factor = 1.0 + (HEALTH_SCALE_PER_LAYER * Math.max(layer, 0));

        var healthAttr = mob.getAttribute(Attributes.MAX_HEALTH);
        if (healthAttr != null) {
            healthAttr.setBaseValue(healthAttr.getBaseValue() * factor);
            mob.setHealth(mob.getMaxHealth());
        }

        var damageAttr = mob.getAttribute(Attributes.ATTACK_DAMAGE);
        if (damageAttr != null) {
            damageAttr.setBaseValue(damageAttr.getBaseValue() * factor);
        }
    }

    private void tagVisibly(Mob mob, int layer) {
        // "No discovery aids" (Tier 1) means findable by looking, not invisible until you already
        // know -- a lightweight visible marker, not a real discovery mechanic (that's Tier 2).
        mob.setCustomName(Component.literal("Boss (Layer " + layer + ")"));
        mob.setCustomNameVisible(true);
        mob.setGlowingTag(true);
    }
}
